# Welcome to the TWClaim Config!
# List of materials that can be used for reinforcement and how many reinforcement points they give
reinforcements:
  - diamond: 10

# Bastions consume fuel to work. Set the fuel types and values here.
bastion-fuel:
  - diamond: 10

# The rate at which bastions consume fuel

# Costs for bastion upgrades
anti-flight:
  - diamond: 10
  - fuel: 10

anti-teleport:
  - diamond: 10
  - fuel: 10

range:
  - diamond: 10
  - fuel: 10

surveillance:
  - diamond: 10
  - fuel: 10

exp-storage:
  - diamond: 10
  - fuel: 10


# The min reinforcement percentage that reinforcement mats can be recovered when someone with perms breaks the block
recover-min: 0

# The radius around the player that the claims map will be generated
map-radius: 4

# The limit of blocks someone can select at once with the claim command
claim-limit: 1000