# Welcome to the TWClaim Config!
# List of materials that can be used for reinforcement and how many reinforcement points they give
reinforcements:
  - diamond: 10

# Reinforcement value subtracted when a block is blown up
explosion-damage: 10
# Reinforcement value subtracted when block would be broken by fire
fire-damage: 5

# Bastions consume fuel to work. Set the fuel types and values here.
bastion-fuel:
  - diamond: 10
  - stone: 5

# The rate at which bastions consume fuel without any upgrades
base-consumption: 10
# The amount of time (minutes) between fuel consumptions
base-consumption-period: 1

# Range of Bastion
bastion-range: 30

# The range of protection around a bastion extender
extender-range: 30

# The fuel cost of extenders
extender-cost: 10

# Costs for bastion upgrades
anti-flight:
  - diamond: 10
  - fuel consumption when active: 10

anti-teleport:
  - diamond: 10
  - fuel consumption when active: 10

surveillance:
  - diamond: 10
  - fuel consumption when active: 10
  - fuel per person spied on: 1

exp-storage:
  - diamond: 10
  - fuel consumption when active: 10
  - fuel per 100 points: 1


# The min reinforcement percentage that reinforcement mats can be recovered when someone with perms breaks the block
recover-min: 0

# The radius around the player that the claims map will be generated
map-radius: 4

# The limit of blocks someone can select at once with the claim command
claim-limit: 1000